name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        platform:
          - amd64
          - armv7
          - arm64
          - ppc64le
          - s390x

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ matrix.platform }}
        push: true
        tags: ghcr.io/${{ github.repository }}/ubuntuxfce:${{ matrix.platform }},ghcr.io/${{ github.repository }}/ubuntuxfce:latest
        annotations: |
          type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image

    - name: Set latest tag for multi-arch image
      if: ${{ matrix.platform == 'linux/amd64' }}
      run: |
        LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker tag "ghcr.io/${LOWERCASE_REPO}/ubuntuxfce:${{ matrix.platform }}" "ghcr.io/${LOWERCASE_REPO}/ubuntuxfce:latest"
        docker push "ghcr.io/${LOWERCASE_REPO}/ubuntuxfce:latest"
