name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image for multiple architectures
      run: |
        TIMESTAMP=$(date +%s)
        LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="ghcr.io/${LOWERCASE_REPO}/ubuntuxfce"
        TAG="${TIMESTAMP}"
        
        # Create a new Buildx builder instance if needed
        docker buildx create --name mybuilder --use
        
        # Build and push multi-architecture image
        docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --file Dockerfile --tag "${IMAGE_NAME}:${TAG}" --tag "${IMAGE_NAME}:latest" --push .
        
        echo "Built and pushed multi-architecture image ${IMAGE_NAME}:${TAG} and ${IMAGE_NAME}:latest"
